# Generated by Django 6.0 on 2026-01-03 14:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_title', models.CharField(help_text='Target job Role', max_length=255)),
                ('job_description', models.TextField(help_text='The raw requirements for the jobs')),
                ('resume_file', models.FileField(upload_to='resume/pdf/')),
                ('overall_match_score', models.FloatField(default=0.0)),
                ('section_match_score', models.JSONField(default=dict)),
                ('retrieved_evidence', models.JSONField(blank=True, default=dict)),
                ('missing_keywords', models.JSONField(blank=True, default=list)),
                ('analysis_summary', models.TextField(blank=True, help_text='AI generated summary for the resume')),
                ('improved_suggestion', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_analysis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Resume Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
