# Generated by Django 6.0 on 2026-02-08 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('resume_file', models.FileField(upload_to='resume/pdf/')),
                ('parsed_resume_data', models.JSONField(blank=True, null=True)),
                ('overall_match_score', models.FloatField(default=0.0)),
                ('section_match_score', models.JSONField(default=dict)),
                ('retrieved_evidence', models.JSONField(default=dict)),
                ('missing_keywords', models.JSONField(default=list)),
                ('analysis_summary', models.TextField(blank=True, null=True)),
                ('improved_suggestion', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_analysis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_history', models.JSONField(default=list)),
                ('current_stage', models.CharField(default='project_manager', max_length=50)),
                ('interview_feedback', models.JSONField(blank=True, null=True)),
                ('verdict', models.CharField(choices=[('PENDING', 'Pending'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicants.resumeanalysis')),
            ],
        ),
    ]
